project:
  type: website
  output-dir: docs

website:
  title: "Seb's blog"
  favicon: "favicon.ico"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sebastian-gerdes/
format:
  html:
    theme: cosmo
    css: styles.css
