project:
  type: 
    website:
      comments:
        utterances:
          repo: sebastian-gerdes/sbloggel2_comments
  output-dir: docs

website:
  title: "Seb's personal blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sebastian-gerdes/
format:
  html:
    theme: cosmo
    css: styles.css



https://github.com/sebastian-gerdes/sbloggel2_comments