project:
  type: website

website:
  # title: "![](/images/favicon.ico) Seb's blog"
  title: "Seb's blog"
  site-url: https://sbloggel.netlify.app/
  description: "Seb's private blog about statistics and other topics"
  favicon: "images/favicon.ico"
  repo-url: https://github.com/sebastian-gerdes/sbloggel
  repo-actions: [source]
  open-graph: true
  # comments: 
  #   hypothesis:
  #     theme: clean
  navbar:
    left:
      # - about.qmd
      - text: About
        file: about.qmd
      - text: Posts
        file: index.qmd
    right:
      - icon: rss
        href: posts.xml
      # - icon: github
      #   href: https://github.com/sebastian-gerdes/
format:
  html:
    theme: cosmo
    css: styles.css
    title-block-banner: false

