project:
  type: website
  # output-dir: docs

website:
  title: "Seb's blog"
  site-url: https://sbloggel.netlify.app/
  description: "Seb's private blog about statistics and other topics"
  favicon: "favicon.ico"
  repo-url: https://github.com/sebastian-gerdes/sbloggel
  repo-actions: [source]
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/sebastian-gerdes/
format:
  html:
    theme: cosmo
    css: styles.css
