---
title: The iris dataset
author: Sebastian Gerdes
date: 2023-07-12
categories:
  - R
toc: true
---

## Init
```{r}
#| label: init
#| message: false
library('tidyverse')
```

## Data preparation
```{r}
#| label: data_preparation
iris_long <- iris |> 
  pivot_longer(cols = -Species, 
               names_to = 'Variable', 
               values_to = 'Value')
```

## Plots
```{r}
#| label: iris_plots
iris_long |> 
  ggplot(aes(Variable, Value, color = Species)) + 
  geom_boxplot()

last_plot() + scale_y_log10() 

iris_long |> 
  ggplot(aes(Variable, Value, color = Species)) + 
  geom_jitter(height = 0)

last_plot() + scale_y_log10() 
```

## Models
```{r}
#| label: iris_models
fitted_model <- 
  lm(Value ~ Species * Variable, 
     data = iris_long)
anova(fitted_model)
plot(fitted_model)

fitted_model <- 
  lm(log(Value) ~ Species * Variable, 
     data = iris_long)
anova(fitted_model)
plot(fitted_model)
```

## Conclusion
* In general, I like the log scale modeling - however there is a problem with the model on log scale:
  * Species setosa is not fit adequately - probably measurement error is not adequately modeled on log scale