---
title: Managing python versions in RStudio
author: Sebastian Gerdes
date: 2023-07-05
categories:
  - Python
toc: true
toc-depth: 4
draft: false
engine: knitr
---

## Ressources
* Good resources are found in the {reticulate} vignettes: [Link](https://cran.r-project.org/web/packages/reticulate/index.html), in particular [this](https://cran.r-project.org/web/packages/reticulate/vignettes/versions.html)
* Link to question on stackoverflow - [Link](https://stackoverflow.com/questions/76745347/how-to-make-quarto-use-the-same-python-environment-that-was-specified-in-rstudio)

```{r}
#| label: init_python
#| include: false
library('reticulate')
use_miniconda(condaenv = 'sbloggel')
py_run_string('x = 10 + 10')
py_run_string('print(x)')
py_version()
py_exe()
py_list_packages(envname = py_exe())
```


# Managing python installation
```{r}
#| eval: false
library('reticulate')
py_discover_config()
py_config()
conda_list()

conda_version()
configure_environment()
conda_create('sbloggel')


conda_install('sbloggel', 'pandas')
miniconda_update()
use_condaenv('sbloggel')
conda_install('sbloggel', 'plotly')
use_condaenv('base')
```


# Install virtual environments to jupyter
* [Link](https://janakiev.com/blog/jupyter-virtual-envs/)


```{bash}
#| eval: false

# Prepare python to enable installation of virtual environments in Jupyter:
pip install --user ipykernel

# Show conda environments and activate:
conda info --envs  
conda activate sbloggel

# Install virtual environment into jupyter:
python -m ipykernel install --user --name=sbloggel
conda activate /Users/seb/Library/r-miniconda-arm64/envs/sbloggel  
```

Start Jupyter from terminal:
```{bash}
#| eval: false
jupyter notebook
```

